name: lint

on:
  pull_request:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**.clang-format'
      - '**.clang-tidy'
  push:
    paths:
      - '**.hpp'
      - '**.cpp'
      - '**.h'
      - '**.c'
      - '**.clang-format'
      - '**.clang-tidy'

permissions:
  contents: read

jobs:
  check-format-and-tidy:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: jidicula/clang-format-action@v4.16.0
      with:
        clang-format-version: '21'
        fallback-style: 'none'

    # no tidy for now I'm too lazy sorry
